version: '8.3'

services:
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=qwer1234
      - MARIADB_DATABASE=poticard
    volumes:
      - ./db:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mariadb://db:3306/poticard
      - DB_USER=root
      - DB_PASS=qwer1234
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/fullchain.crt:/etc/nginx/ssl/fullchain.crt
      - /root/private.key:/etc/nginx/ssl/private.key
    depends_on:
      - backend